# -*- coding: utf-8 -*-
"""Project_JC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UnuWtrsB_5aflz6F2mcLeIbjtemPF54t
"""

pip install streamlit pandas numpy

!mkdir hdb_resale_app
!cd hdb_resale_app

import streamlit as st

# Function 1: HDB Resale Flat Affordability Calculator
def affordability_calculator():
    st.title('HDB Resale Flat Affordability Calculator')

    # User Inputs
    income = st.number_input('Enter your monthly household income (SGD)', min_value=0)
    cpf_savings = st.number_input('Enter your total CPF savings available (SGD)', min_value=0)
    cash_savings = st.number_input('Enter your cash savings available (SGD)', min_value=0)
    grant_eligibility = st.selectbox('Are you eligible for any grants?', ['Yes', 'No'])

    # Simple calculations
    grant_amount = 50000 if grant_eligibility == 'Yes' else 0  # Example grant amount for simplicity
    total_savings = cpf_savings + cash_savings + grant_amount
    max_loan = income * 60  # A simple calculation of loan eligibility (income * 60 months)

    # Display Results
    if st.button('Calculate'):
        max_price = total_savings + max_loan
        st.write(f'Based on your input, you can afford a resale flat priced up to S${max_price:,.0f}.')

# Function 2: HDB Resale Process Navigator
def resale_process_navigator():
    st.title('HDB Resale Process Navigator')

    # User Inputs
    first_time_buyer = st.selectbox('Are you a first-time buyer?', ['Yes', 'No'])
    family_proximity = st.selectbox('Are you purchasing a flat near your family?', ['Yes', 'No'])

    # Generate Process Flow
    if st.button('Generate Process Flow'):
        st.subheader('Steps to Buying an HDB Resale Flat')
        st.write('Step 1: Check your eligibility.')
        st.write('Step 2: Search for resale flats on HDB website.')
        st.write('Step 3: Contact seller and negotiate price. Obtain Option to Purchase (OTP).')

        if first_time_buyer == 'Yes':
            st.write('Step 4: Apply for first-time buyer grants (e.g., Family Grant).')

        if family_proximity == 'Yes':
            st.write('Step 5: Apply for Proximity Housing Grant.')
        else:
            st.write('Step 5: No Proximity Housing Grant available.')

        st.write('Step 6: Arrange for HDB-approved valuation of the flat.')
        st.write('Step 7: Exercise your Option to Purchase.')
        st.write('Step 8: Complete the necessary paperwork and attend HDB appointments.')

# "About Us" Page
def about_us_page():
    st.title("About Us")
    st.write("""
        This application is designed to assist potential buyers in navigating the complex process of buying an HDB resale flat in Singapore.
        We provide two main tools:
        1. **Affordability Calculator**: Helps you determine the maximum flat price you can afford based on your financial information.
        2. **Resale Process Navigator**: Guides you step-by-step through the process of purchasing an HDB resale flat.

        **Data Sources**:
        - HDB official website for grant and eligibility information.
        - CPF Board for financial calculations related to CPF savings and usage.
    """)

# "Methodology" Page
def methodology_page():
    st.title("Methodology")
    st.write("""
        The following outlines the methodology used in this application:

        **Affordability Calculator**:
        - The calculator takes into account your CPF savings, cash savings, and eligible grants to calculate the total savings available.
        - Your loan eligibility is estimated by multiplying your monthly income by 60 (representing a loan term of 5 years).
        - The total affordable price is the sum of your total savings and your estimated loan eligibility.

        **Resale Process Navigator**:
        - Based on user input, the navigator generates a customized step-by-step guide to the HDB resale process.
        - The steps are tailored depending on whether you are a first-time buyer and whether you're purchasing near your family for additional grant eligibility.

        Flowcharts for each of the use cases:
    """)
    st.image('affordability_calculator_flowchart.png')  # You can add a flowchart image here
    st.image('resale_process_navigator_flowchart.png')

# Main Navigation
def main():
    st.sidebar.title("Navigation")
    page = st.sidebar.radio("Go to", ["Home", "Affordability Calculator", "Resale Process Navigator", "About Us", "Methodology"])

    if page == "Home":
        st.title("Welcome to the HDB Resale Assistant")
        st.write("Use the sidebar to navigate through the app.")

    elif page == "Affordability Calculator":
        affordability_calculator()

    elif page == "Resale Process Navigator":
        resale_process_navigator()

    elif page == "About Us":
        about_us_page()

    elif page == "Methodology":
        methodology_page()

if __name__ == "__main__":
    main()